package app.phonepost


class LanguagesListUtil {
    companion object {
        public val languages = ArrayList<LanguageHolder>().apply {
            this.add(LanguageHolder("हिन्दी (भारत)", "hi-IN", "हिन्दी"))
            this.add(LanguageHolder("తెలుగు (భారతదేశం)", "te-IN", "తెలుగు"))
            this.add(LanguageHolder("বাংলা (ভারত)", "bn-IN", "বাংলা"))
            this.add(LanguageHolder("ગુજરાતી (ભારત)", "gu-IN", "ગુજરાતી"))
            this.add(LanguageHolder("ಕನ್ನಡ (ಭಾರತ)", "kn-IN", "ಕನ್ನಡ"))
            this.add(LanguageHolder("മലയാളം (ഇന്ത്യ)", "ml-IN", "മലയാളം"))
            this.add(LanguageHolder("मराठी (भारत)", "mr-IN", "मराठी"))
            this.add(LanguageHolder("தமிழ் (இந்தியா)", "ta-IN", "தமிழ்"))
            this.add(LanguageHolder("اردو (بھارت)", "ur-IN", "اردو"))
            this.add(LanguageHolder("English (India)", "en-IN", "English"))
            this.add(LanguageHolder("Afrikaans (Suid-Afrika)", "af-ZA", "Afrikaans"))
            this.add(LanguageHolder("አማርኛ (ኢትዮጵያ)", "am-ET", "አማርኛ"))
            this.add(LanguageHolder("Հայ (Հայաստան)", "hy-AM", "Հայ"))
            this.add(LanguageHolder("Azərbaycan (Azərbaycan)", "az-AZ", "Azərbaycan"))
            this.add(LanguageHolder("Bahasa Indonesia (Indonesia)", "id-ID", "Bahasa Indonesia"))
            this.add(LanguageHolder("Bahasa Melayu (Malaysia)", "ms-MY", "Bahasa Melayu"))
            this.add(LanguageHolder("বাংলা (বাংলাদেশ)", "bn-BD", "বাংলা"))
            this.add(LanguageHolder("Català (Espanya)", "ca-ES", "Català"))
            this.add(LanguageHolder("Čeština (Česká republika)", "cs-CZ", "Čeština"))
            this.add(LanguageHolder("Dansk (Danmark)", "da-DK", "Dansk"))
            this.add(LanguageHolder("Deutsch (Deutschland)", "de-DE", "Deutsch"))
            this.add(LanguageHolder("English (Australia)", "en-AU", "English"))
            this.add(LanguageHolder("English (Canada)", "en-CA", "English"))
            this.add(LanguageHolder("English (Ghana)", "en-GH", "English"))
            this.add(LanguageHolder("English (Great Britain)", "en-GB", "English"))
            this.add(LanguageHolder("English (Ireland)", "en-IE", "English"))
            this.add(LanguageHolder("English (Kenya)", "en-KE", "English"))
            this.add(LanguageHolder("English (New Zealand)", "en-NZ", "English"))
            this.add(LanguageHolder("English (Nigeria)", "en-NG", "English"))
            this.add(LanguageHolder("English (Philippines)", "en-PH", "English"))
            this.add(LanguageHolder("English (Singapore)", "en-SG", "English"))
            this.add(LanguageHolder("English (South Africa)", "en-ZA", "English"))
            this.add(LanguageHolder("English (Tanzania)", "en-TZ", "English"))
            this.add(LanguageHolder("English (United States)", "en-US", "English"))
            this.add(LanguageHolder("Español (Argentina)", "es-AR", "Español"))
            this.add(LanguageHolder("Español (Bolivia)", "es-BO", "Español"))
            this.add(LanguageHolder("Español (Chile)", "es-CL", "Español"))
            this.add(LanguageHolder("Español (Colombia)", "es-CO", "Español"))
            this.add(LanguageHolder("Español (Costa Rica)", "es-CR", "Español"))
            this.add(LanguageHolder("Español (Ecuador)", "es-EC", "Español"))
            this.add(LanguageHolder("Español (El Salvador)", "es-SV", "Español"))
            this.add(LanguageHolder("Español (España)", "es-ES", "Español"))
            this.add(LanguageHolder("Español (Estados Unidos)", "es-US", "Español"))
            this.add(LanguageHolder("Español (Guatemala)", "es-GT", "Español"))
            this.add(LanguageHolder("Español (Honduras)", "es-HN", "Español"))
            this.add(LanguageHolder("Español (México)", "es-MX", "Español"))
            this.add(LanguageHolder("Español (Nicaragua)", "es-NI", "Español"))
            this.add(LanguageHolder("Español (Panamá)", "es-PA", "Español"))
            this.add(LanguageHolder("Español (Paraguay)", "es-PY", "Español"))
            this.add(LanguageHolder("Español (Perú)", "es-PE", "Español"))
            this.add(LanguageHolder("Español (Puerto Rico)", "es-PR", "Español"))
            this.add(LanguageHolder("Español (República Dominicana)", "es-DO", "Español"))
            this.add(LanguageHolder("Español (Uruguay)", "es-UY", "Español"))
            this.add(LanguageHolder("Español (Venezuela)", "es-VE", "Español"))
            this.add(LanguageHolder("Euskara (Espainia)", "eu-ES", "Euskara"))
            this.add(LanguageHolder("Filipino (Pilipinas)", "fil-PH", "Filipino"))
            this.add(LanguageHolder("Français (Canada)", "fr-CA", "Français"))
            this.add(LanguageHolder("Français (France)", "fr-FR", "Français"))
            this.add(LanguageHolder("Galego (España)", "gl-ES", "Galego"))
            this.add(LanguageHolder("ქართული (საქართველო)", "ka-GE", "ქართული"))
            this.add(LanguageHolder("Hrvatski (Hrvatska)", "hr-HR", "Hrvatski"))
            this.add(LanguageHolder("IsiZulu (Ningizimu Afrika)", "zu-ZA", "IsiZulu"))
            this.add(LanguageHolder("Íslenska (Ísland)", "is-IS", "Íslenska"))
            this.add(LanguageHolder("Italiano (Italia)", "it-IT", "Italiano"))
            this.add(LanguageHolder("Jawa (Indonesia)", "jv-ID", "Jawa"))
            this.add(LanguageHolder("ភាសាខ្មែរ (កម្ពុជា)", "km-KH", "ភាសាខ្មែរ"))
            this.add(LanguageHolder("ລາວ (ລາວ)", "lo-LA", "ລາວ"))
            this.add(LanguageHolder("Latviešu (latviešu)", "lv-LV", "Latviešu"))
            this.add(LanguageHolder("Lietuvių (Lietuva)", "lt-LT", "Lietuvių"))
            this.add(LanguageHolder("Magyar (Magyarország)", "hu-HU", "Magyar"))
            this.add(LanguageHolder("Nederlands (Nederland)", "nl-NL", "Nederlands"))
            this.add(LanguageHolder("नेपाली (नेपाल)", "ne-NP", "नेपाली"))
            this.add(LanguageHolder("Norsk bokmål (Norge)", "nb-NO", "Norsk bokmål"))
            this.add(LanguageHolder("Polski (Polska)", "pl-PL", "Polski"))
            this.add(LanguageHolder("Português (Brasil)", "pt-BR", "Português"))
            this.add(LanguageHolder("Português (Portugal)", "pt-PT", "Português"))
            this.add(LanguageHolder("Română (România)", "ro-RO", "Română"))
            this.add(LanguageHolder("සිංහල (ශ්රී ලංකාව)", "si-LK", "සිංහල"))
            this.add(LanguageHolder("Slovenčina (Slovensko)", "sk-SK", "Slovenčina"))
            this.add(LanguageHolder("Slovenščina (Slovenija)", "sl-SI", "Slovenščina"))
            this.add(LanguageHolder("Urang (Indonesia)", "su-ID", "Urang"))
            this.add(LanguageHolder("Swahili (Tanzania)", "sw-TZ", "Swahili"))
            this.add(LanguageHolder("Swahili (Kenya)", "sw-KE", "Swahili"))
            this.add(LanguageHolder("Suomi (Suomi)", "fi-FI", "Suomi"))
            this.add(LanguageHolder("Svenska (Sverige)", "sv-SE", "Svenska"))
            this.add(LanguageHolder("தமிழ் (சிங்கப்பூர்)", "ta-SG", "தமிழ்"))
            this.add(LanguageHolder("தமிழ் (இலங்கை)", "ta-LK", "தமிழ்"))
            this.add(LanguageHolder("தமிழ் (மலேசியா)", "ta-MY", "தமிழ்"))
            this.add(LanguageHolder("Tiếng Việt (Việt Nam)", "vi-VN", "Tiếng Việt"))
            this.add(LanguageHolder("Türkçe (Türkiye)", "tr-TR", "Türkçe"))
            this.add(LanguageHolder("اردو (پاکستان)", "ur-PK", "اردو"))
            this.add(LanguageHolder("Ελληνικά (Ελλάδα)", "el-GR", "Ελληνικά"))
            this.add(LanguageHolder("Български (България)", "bg-BG", "Български"))
            this.add(LanguageHolder("Русский (Россия)", "ru-RU", "Русский"))
            this.add(LanguageHolder("Српски (Србија)", "sr-RS", "Српски"))
            this.add(LanguageHolder("Українська (Україна)", "uk-UA", "Українська"))
            this.add(LanguageHolder("עברית (ישראל)", "he-IL", "עברית"))
            this.add(LanguageHolder("العربية (إسرائيل)", "ar-IL", "العربية"))
            this.add(LanguageHolder("العربية (الأردن)", "ar-JO", "العربية"))
            this.add(LanguageHolder("العربية (الإمارات)", "ar-AE", "العربية"))
            this.add(LanguageHolder("العربية (البحرين)", "ar-BH", "العربية"))
            this.add(LanguageHolder("العربية (الجزائر)", "ar-DZ", "العربية"))
            this.add(LanguageHolder("العربية (السعودية)", "ar-SA", "العربية"))
            this.add(LanguageHolder("العربية (العراق)", "ar-IQ", "العربية"))
            this.add(LanguageHolder("العربية (الكويت)", "ar-KW", "العربية"))
            this.add(LanguageHolder("العربية (المغرب)", "ar-MA", "العربية"))
            this.add(LanguageHolder("العربية (تونس)", "ar-TN", "العربية"))
            this.add(LanguageHolder("العربية (عُمان)", "ar-OM", "العربية"))
            this.add(LanguageHolder("العربية (فلسطين)", "ar-PS", "العربية"))
            this.add(LanguageHolder("العربية (قطر)", "ar-QA", "العربية"))
            this.add(LanguageHolder("العربية (لبنان)", "ar-LB", "العربية"))
            this.add(LanguageHolder("العربية (مصر)", "ar-EG", "العربية"))
            this.add(LanguageHolder("فارسی (ایران)", "fa-IR", "فارسی"))
            this.add(LanguageHolder("ไทย (ประเทศไทย)", "th-TH", "ไทย"))
            this.add(LanguageHolder("한국어 (대한민국)", "ko-KR", "한국어"))
            this.add(LanguageHolder("國語 (台灣)", "zh-TW", "國語"))
            this.add(LanguageHolder("廣東話 (香港)", "yue-Hant-HK", "廣東話"))
            this.add(LanguageHolder("日本語（日本）", "ja-JP", "日本語"))
            this.add(LanguageHolder("普通話 (香港)", "zh-HK", "普通話"))
            this.add(LanguageHolder("普通话 (中国大陆)", "zh", "普通话"))

        }

        val map = HashMap<String, LanguageHolder>()

        init {
            languages.forEach {
                map.put(it.languageCode, it)
            }
        }
    }
}